### ISSUE TITLE
Deprecation notice when used with SvelteKit / svelte-preprocess due to install() appending script with 'type' instead of 'lang' parameter

### ISSUE THREAD

**Issue by JoseAlmeidaCamenAi** [idmadj/ga-gtag#8]
I am using this package to include gtag on a SvelteKit single page application, and getting the following:

`[svelte-preprocess] Deprecation notice: using the "type" attribute is no longer recommended and will be removed in the next major version. Please use the "lang" attribute instead.`

I think this is because the install() method of this package is appending a <script> tag with parameter **type="text/javascript"** instead of **lang="text/javascript"** like all other script tags used in my app.

Is that something that can be fixed? 
I think I could give it a try but first would need to learn how to contribute / open PRs in public repositories like this as I haven't really done it before.

**Comment by idmadj** [comment]
Thanks for opening the issue.

If I'm not mistaken, the `lang` and `language` attributes have been deprecated for a little while now, so it's a little suspect that SvelteKit would recommend using them instead. HTML doesn't have "versions" either as it is a living standard, so that error might be referring to something else.

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attributes), and by extension the [HTML standard](https://html.spec.whatwg.org/multipage/scripting.html#the-script-element), the `type` attribute should be used, but it is recommended to "omit the attribute if the script refers to JavaScript code". On top of that the newer Google tag documentation omits the tag, so I think the best route here is to get rid of it entirely.

I've published version 1.1.7 with this change.
